"use client";

import "./global.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Providers } from "./providers";
import { Navbar } from "@/components/navbar/navbar";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Infinite scroller",
	description: "Generated by Siim Tali",
};

type Props = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<Navbar />
					<Box
						height="calc(100vh - var(--chakra-space-16))"
						marginTop={16}
						position="absolute"
						width="100vw"
					>
						<div
							className="content"
							style={{ height: "100%", width: "100%" }}
						>
							{children}
						</div>
					</Box>
				</Providers>
			</body>
		</html>
	);
}
